# Site settings
title: Mehdi Mehdikhani
email: mehdi.erc@gmail.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mehdierc.github.io" # the base hostname & protocol for your site
twitter_username: #MehdiMehdikhani
github_username: #mehdierc
linkedin_username: mehdimehdikhani
google_plus_username: #MehdiMehdikhani
facebook_username: mehdikhani.mehdi
youtube_channel: #UCYVrwNGymMMvXI9Oqd3JYHg
instagram_username: #mehdikhanimehdi
# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Research Asistant"
excerpt_separator: <!--more-->

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
